services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - MONGODB_URL=mongodb+srv://thakurdivya220703:thakur220703@cluster0.rzmzycs.mongodb.net/GupShup?retryWrites=true&w=majority
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    restart: always
